name: weekly

on:
  schedule:
    # At 15:28 on a Thursday
    - cron: "28 15 * * 4"
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          component: llvm-tools-preview
          target: thumbv7em-none-eabihf
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-generate
          version: latest
          use-tool-cache: true
      - name: Generate the template
        run: cargo generate --git https://github.com/mciantyre/teensy4-rs-template --name hello-world
      - name: Check the template
        run: cd hello-world && cargo build