name: weekly

on:
  schedule:
    # At 15:28 on a Thursday
    - cron: "28 15 * * 4"
  push:
    branches: [ master, feature/faster-ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview
          target: thumbv7em-none-eabihf
          override: true
      - name: Install cargo-generate
        env:
          PACKAGE: cargo-generate-v0.5.0-x86_64-unknown-linux-musl
        run: |
          curl -LJO https://github.com/ashleygwilliams/cargo-generate/releases/latest/download/${PACKAGE}.tar.gz && \
          tar -xvf ${PACKAGE}.tar.gz && \
          cp ${PACKAGE}/cargo-generate $(dirname $(which cargo)) && \
          cargo generate --help
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true
      - name: Generate the template
        run: cargo generate --git https://github.com/mciantyre/teensy4-rs-template --name hello-world
      - name: Check the template
        run: cd hello-world && cargo objcopy -- -O ihex hello-world.hex